import type { SessionConfigOption } from "@agentclientprotocol/sdk";
import type { Attachment } from "../lib/attachments";
import type { DesktopShortcutPlatform } from "../lib/desktop-commands";
import type { WorkbenchTabId } from "../lib/workbench-tabs";
import type { ActiveSessionState } from "./active-session-state.svelte";
import type { ConnectionStatus } from "./connection.svelte";
import type { DesktopCommandServices } from "./desktop-command-services";
import type { DesktopConversationServices } from "./desktop-conversation-services";
import type { DesktopInteractionServices } from "./desktop-interaction-services.svelte";
import type { DesktopModelServices } from "./desktop-model-services";
import type { DesktopPresentationState } from "./desktop-presentation-state.svelte";
import type { DesktopProjectActionServices } from "./desktop-project-action-services";
import type { DesktopProjectServices } from "./desktop-project-services";
import type { DesktopPromptActionServices } from "./desktop-prompt-action-services";
import type { DesktopPromptServices } from "./desktop-prompt-services";
import type { createDesktopSessionOrchestration } from "./desktop-session-orchestration";
import type { DesktopSessionServices } from "./desktop-session-services";
import type { DesktopSessionTransitionServices } from "./desktop-session-transition-services";
import type { DesktopWorkbenchGitServices } from "./desktop-workbench-git-services";
import type { DesktopWorkspaceServices } from "./desktop-workspace-services";
import type { createErrorState } from "./error-state.svelte";
import type { createTranscriptAttachmentController } from "./transcript-attachments";
import type { createTranscriptScrollController } from "./transcript-scroll.svelte";

type ErrorState = ReturnType<typeof createErrorState>;
type SessionOrchestration = ReturnType<typeof createDesktopSessionOrchestration>;
type TranscriptAttachments = ReturnType<typeof createTranscriptAttachmentController>;
type TranscriptScroll = ReturnType<typeof createTranscriptScrollController>;

export type DesktopViewModelServicesOptions = {
  platform: DesktopShortcutPlatform;
  workspace: () => string;
  status: () => ConnectionStatus;
  clientAvailable: () => boolean;
  operationRunning: () => boolean;
  dragActive: () => boolean;
  activeWorkbenchTabId: () => WorkbenchTabId | null;
  promptText: () => string;
  promptAttachments: () => Attachment[];
  changingConfig: () => string | null;
  displayedConfigOptions: () => SessionConfigOption[];
  reconnect: () => void | Promise<void>;
  state: ActiveSessionState;
  errors: ErrorState;
  sessions: DesktopSessionServices;
  project: DesktopProjectServices;
  prompt: DesktopPromptServices;
  transitions: DesktopSessionTransitionServices;
  conversation: DesktopConversationServices;
  promptActions: DesktopPromptActionServices;
  projectActions: DesktopProjectActionServices;
  workbenchGit: DesktopWorkbenchGitServices;
  model: DesktopModelServices;
  commands: DesktopCommandServices;
  interactions: DesktopInteractionServices;
  presentation: DesktopPresentationState;
  workspaceController: DesktopWorkspaceServices["controller"];
  transcriptScroll: TranscriptScroll;
  transcriptAttachments: TranscriptAttachments;
  orchestration: SessionOrchestration;
};
