/** Authored setting metadata for search; never populate this from config values or rendered DOM. */
export interface SettingsSearchEntry {
  readonly id: string;
  readonly section: string;
  readonly label: string;
  readonly description?: string;
  readonly synonyms: readonly string[];
}

export function settingsFieldId(label: string): string {
  return label.toLocaleLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/gu, "")
    .replace(/[^a-z0-9]+/gu, "-").replace(/^-|-$/gu, "");
}

const desktop = (section: string, label: string, description: string, ...synonyms: string[]): SettingsSearchEntry => ({
  id: settingsFieldId(label), section: `desktop-${section}`, label, description, synonyms,
});
const tools = (section: string, label: string, description = "", ...synonyms: string[]): SettingsSearchEntry => ({
  id: settingsFieldId(label), section: `pi-tools-suite-${section}`, label, ...(description ? { description } : {}), synonyms,
});

// This catalogue is deliberately authored independently of JSONC, schemas' values, and DOM text.
export const SETTINGS_SEARCH_CATALOG: readonly SettingsSearchEntry[] = [
  desktop("general", "Ignore context files", "Do not discover AGENTS.md or CLAUDE.md for Desktop sessions.", "agents", "claude"),
  desktop("general", "System notifications", "Send native notifications while this Pix window is in the background.", "alerts"),
  desktop("models", "Default model", "Provider/model identifier used for new Desktop sessions.", "model picker"),
  desktop("models", "Default thinking", "Thinking budget applied when a new session starts.", "reasoning"),
  desktop("models", "Default fallbacks", "Ordered models tried after the default model.", "fallback models"),
  desktop("models", "Automatic model routing", "Route the first prompt to a semantic task tier before session creation.", "auto", "routing"),
  desktop("models", "Auto by default", "Start each new conversation draft in Auto.", "automatic"),
  desktop("models", "Router model", "Short classification call used only by Auto.", "classification"),
  desktop("models", "Router fallbacks", "Ordered models tried when the primary router is unavailable.", "fallbacks"),
  desktop("models", "Routing fallback tier", "Tier used if every router model fails.", "default tier"),
  desktop("models", "Routing tiers", "Semantic task classes available to the router.", "task tiers"),
  desktop("models", "Visible models", "Choose which models appear in the Desktop model picker.", "model visibility"),
  desktop("assistant", "Knowledge review model", "Model for knowledge-base AI review sessions.", "knowledge base"),
  desktop("assistant", "Prompt enhancer model", "Model used when Desktop improves a draft prompt.", "prompt improvement"),
  desktop("assistant", "Prompt enhancer fallbacks", "Ordered prompt-enhancer fallback models.", "prompt improvement"),
  desktop("assistant", "Autocomplete model", "Model used for inline prompt completions.", "inline completion", "автодополнение", "авто-пополнение", "автозавершение"),
  desktop("assistant", "Autocomplete fallbacks", "Ordered fallback models for inline completions.", "fallbacks", "автодополнение", "авто-пополнение"),
  desktop("assistant", "Typing debounce", "Milliseconds to wait after typing before requesting a completion.", "delay"),
  desktop("assistant", "Request timeout", "Hard timeout in milliseconds for a completion request.", "deadline"),
  desktop("assistant", "Completion tokens", "Maximum output tokens for autocomplete.", "token limit"),
  desktop("assistant", "Prompt token budget", "Maximum input prompt tokens sent to autocomplete.", "input tokens"),
  desktop("assistant", "Recent messages", "Conversation messages included as autocomplete context.", "history", "conversation context"),
  desktop("assistant", "Semantic search", "Separate opt-ins: authored settings metadata, or explicitly saved session names and their search queries, can be sent to OpenRouter for embeddings. First-message fallback titles, conversation history and attachments stay local.", "search", "session titles", "OpenRouter", "Perplexity"),
  desktop("assistant", "Session title model", "Model used to generate compact session titles.", "title generation"),
  desktop("assistant", "Session title fallbacks", "Ordered session-title fallback models.", "fallbacks"),
  desktop("observer", "Passive observer", "Enable the passive observer in new Desktop sessions.", "heads up"),
  desktop("voice", "Deepgram API key", "Stored only in the Desktop user profile for voice dictation.", "voice", "dictation", "secret"),
  desktop("voice", "Language", "Deepgram language code sent to speech recognition.", "dictation"),
  desktop("voice", "Speech model", "Deepgram speech-to-text model.", "dictation"),
  desktop("editor", "File editor", "Application used by Project and Preview open-in-editor actions.", "external editor"),
  desktop("source-control", "CI fix model", "Model used by Fix with AI when CI fails.", "git", "continuous integration"),
  desktop("source-control", "Review model", "Model and thinking level used for Source Control diff review.", "git"),
  desktop("source-control", "Review fallbacks", "Ordered fallback models for Git diff review.", "git"),
  desktop("source-control", "Commit message model", "Model used to generate Git commit messages.", "git"),
  desktop("source-control", "Commit message fallbacks", "Ordered fallback models for Git commit messages.", "git"),
  tools("general", "Tools Suite", "Enable or disable the complete pi-tools-suite extension.", "suite"),
  tools("general", "Modules", "Choose which built-in modules are enabled.", "extensions"),
  tools("general", "Built-in agents", "Choose which bundled async-subagent roles are available.", "subagents"),
  tools("general", "Comment checker", "Warn when newly added comments look like generated commentary.", "comments"),
  tools("general", "Comment strictness", "Strictness for generated-comment warnings.", "comments"),
  tools("general", "Secret session hygiene", "Redact detected secret material from session history.", "redaction"),
  tools("general", "Secret redaction notifications", "Show a warning when secret material is redacted.", "alerts"),
  tools("subagents", "Economy mode", "Skip frontier models marked Expensive for sub-agent roles.", "cost"),
  tools("subagents", "Frontier models", "Preference order for oracle and review roles.", "subagents"),
  tools("automation", "Todo thinking", "Allow todo items to switch and restore model thinking levels.", "reasoning"),
  tools("automation", "Todo thinking limits", "Per-task thinking-level overrides.", "reasoning"),
  tools("automation", "Lookup model", "Vision-capable helper model used by image lookup.", "image search"),
  tools("automation", "Lookup fallbacks", "Ordered fallback models for image lookup.", "image search"),
  tools("dcp", "DCP", "Enable Dynamic Context Pruning.", "context pruning"),
  tools("dcp", "Debug logging", "Write DCP events to the rotating debug log.", "logs"),
  tools("dcp", "Debug log max bytes", "Maximum rotating DCP debug-log size.", "logs"),
  tools("dcp", "Debug log backups", "Number of rotating DCP debug-log backups.", "logs"),
  tools("dcp", "Manual mode", "Enable explicit/manual DCP mode.", "compression"),
  tools("dcp", "Minimum context", "Target context after compression.", "threshold"),
  tools("dcp", "Maximum context", "Context pressure threshold before compression.", "threshold"),
  tools("dcp", "Absolute minimum context", "Absolute target context token limit.", "tokens"),
  tools("dcp", "Absolute maximum context", "Absolute context pressure limit.", "tokens"),
  tools("dcp", "Per-model context percentages", "Per-model minimum/maximum context overrides.", "thresholds"),
  tools("dcp", "Per-model context limits", "Absolute token limits by model.", "tokens"),
  tools("dcp", "Summary buffer", "Context reserved for generated summaries.", "compression"),
  tools("dcp", "Nudge frequency", "Inject a compression nudge every N context events.", "reminder"),
  tools("dcp", "Iteration nudge threshold", "Tool calls before nudging to compress.", "reminder"),
  tools("dcp", "Nudge force", "Strength of compression nudges.", "reminder"),
  tools("dcp", "Protected tools", "Tool outputs protected from compression and pruning.", "preserve"),
  tools("dcp", "Protect tagged content", "Preserve tagged content during context pruning.", "preserve"),
  tools("dcp", "Protect user messages", "Preserve user messages during context pruning.", "preserve"),
  tools("dcp", "Auto candidates", "Enable automatic compression-candidate selection.", "compression"),
  tools("dcp", "Auto-candidate context threshold", "Context threshold for candidate selection.", "compression"),
  tools("dcp", "Auto-candidate recent turns", "Recent turns retained during automatic compression.", "history"),
  tools("dcp", "Auto-candidate minimum messages", "Minimum message count before candidate selection.", "compression"),
  tools("dcp", "Auto-candidate minimum tokens", "Minimum token count before candidate selection.", "compression"),
  tools("dcp", "Message mode", "Enable message-mode compression suggestions.", "suggestions"),
  tools("dcp", "Message-mode context threshold", "Context threshold for message-mode suggestions.", "compression"),
  tools("dcp", "Message-mode recent turns", "Recent turns retained in message-mode suggestions.", "history"),
  tools("dcp", "Message-mode medium tokens", "Medium compression suggestion token size.", "tokens"),
  tools("dcp", "Message-mode high tokens", "High compression suggestion token size.", "tokens"),
  tools("dcp", "Message-mode suggestions", "Maximum message-mode suggestions.", "compression"),
  tools("dcp", "Automatic compression", "Allow autonomous compression after pressure gates.", "compress"),
  tools("dcp", "Auto-compress patience", "Patience before automatic compression.", "compress"),
  tools("dcp", "Summarizer models", "Ordered models used for generated compression summaries.", "summarize"),
  tools("dcp", "Summarizer fallbacks", "Fallback models for generated compression summaries.", "summarize"),
  tools("dcp", "Summarizer timeout", "Per-summarizer deadline in milliseconds.", "summarize"),
  tools("dcp", "Emergency current-turn pruning", "Enable bounded same-turn emergency pruning.", "context"),
  tools("dcp", "Emergency hard context", "Hard context threshold for emergency pruning.", "threshold"),
  tools("dcp", "Emergency target context", "Target context for emergency pruning.", "threshold"),
  tools("dcp", "Emergency patience", "Patience before emergency pruning.", "context"),
  tools("dcp", "Emergency recent tool pairs", "Tool-call pairs retained during emergency pruning.", "history"),
  tools("dcp", "Emergency minimum output tokens", "Minimum output tokens before emergency pruning.", "tokens"),
  tools("dcp", "Emergency max suggestions", "Maximum emergency pruning suggestions.", "context"),
  tools("dcp", "Emergency protected tools", "Tools protected from emergency pruning.", "preserve"),
  tools("dcp", "Protected file patterns", "File path globs protected from pruning.", "files"),
  tools("dcp", "Per-model DCP overrides", "Wildcard-aware model policy overrides.", "context"),
  tools("context", "Repository discovery profile", "Choose baseline or native compact repository discovery.", "index", "repo"),
  tools("integrations", "Registry remote", "Private Git remote for reusable skills and agents.", "registry"),
  tools("integrations", "Registry branch", "Git branch used by the resource registry.", "registry"),
  tools("integrations", "Registry project key", "Optional explicit registry project key.", "registry"),
  tools("integrations", "Terminal bell", "Play the terminal bell sound on completion or error.", "sound"),
  tools("integrations", "Prompt commands", "Slash-command definitions keyed by command name.", "slash commands"),
  tools("integrations", "Tool rendering", "Default and per-tool rendering rules.", "display"),
  tools("integrations", "Language servers", "Language server definitions including binaries and arguments.", "LSP"),
];
